# Local IspellDict: en
#+STARTUP: showeverything
#+SPDX-FileCopyrightText: 2017-2020 Mo, Yilin
#+SPDX-License-Identifier: CC-BY-SA-4.0

# Apply standard settings of oer-reveal.
#+INCLUDE: "~/.emacs.d/oer-reveal-org/config.org"

# Use custom title slide.
#+REVEAL_TITLE_SLIDE: title-slide.html

# Use 16:9 aspect ratio
#+REVEAL_EXTRA_OPTIONS: width: 1280, height: 720

# Generate bibliography with LaTeX
#+LATEX_HEADER: \usepackage[backend=biber,style=alphabetic]{biblatex}
#+LATEX_HEADER: \addbibresource{references.bib}

#+TITLE: 信息物理系统
#+AUTHOR: 莫一林(清华大学  自动化系)
#+DATE:  信息物理系统专委会 (Aug 21, 2020)

#+KEYWORDS: Cyber-Physical System, Networked Control, Security, Control
#+DESCRIPTION: A brief overview of the current researches on control and CPS.

* Introduction
** Definition of Cyber-Physical System
 
** Hybrid Systems
   
** Sensor Networks

** Networked Control System   

* Networked Control 

** Control over Networks
   
- Communication is *imperfect*: quantization, delay, packet drops
- Communication is *expensive*: offline scheduling, event-based scheduling
- *Multiple participants* and *local information*: multi-agent system


  
* CPS Security and Privacy 

** Security Risks 
  - The next generation CPS: *Smart Grids*, *Smart Buildings*, *Internet of Things*, will make extensive use of widespread sensing and networking.
  - As the CPSs become "/smarter/", they are also more vulnerable to malicious attacks.
 {{{revealgrid(1, "./smartcps.grid", 40, 3, 1, "\"ga1 ga2 ga3\"")}}}
   
*** The First CPS Malware: Stuxnet

  - Stuxnet is the first discovered malware that spies on and subverts industrial control systems. It was discovered in June 2010.
   {{{revealimg("./stuxnet.meta","Stuxnet Incident","auto",nil,'none)}}}
   
*** Threats to Industrial Control Systems
   
- In FY 2016, ICS-CERT received *290* incidents. The scope of incidents includes: {{{reveallicense("./cert.meta","auto",nil,'none)}}}
  * Unauthorized access, 
  * Exploitation of zero-day vulnerabilities,  
  * Malware infections within air-gapped control system networks.

*** Attack Through Supply Chain

- 70% of the components for Boeing 787 are manufactured by other suppliers cite:Tang2009
   {{{revealimg("./boeing.meta","Supply Chain for Boeing 787","auto",nil,'none)}}}
   
*** Black Energy

- A Successful attack on *critical infrastructure* can be devastating.
 {{{revealgrid(2, "./powergridattack.grid", 70, 2, 2, "\"ga1 ga2 \" \"ga3 ga3\"")}}}

** Cyber-Physical Security
   
- CIA Triad: *Confidentiality*, *Integrity*, *Availability*
- A case study for smart grid cite:Mo2011
|                 | Control Signal                | Measurements                   | Software           |
| Confidentiality | Exposure of System Structure  | Unauthorized Access            | Piracy             |
| Integrity       | *Changes of Control Command*  | *Incorrect Data*              | *Malicious Software* |
| Availability    | *Inability to Control the Grid* | *Unavailability of Measurements* | N/A                |
 

*** Threat Modelling 

- cite:Teixeira2015 proposes a 3-dimension attack space:{{{reveallicense("./cpsattackspace.meta","auto",nil,'none)}}}
  - *System Knowledge*: Knowledge of off-line system parameters
  - *Disclosure Resources*: Knowledge of on-line signals
  - *Disruption Resources*: Manipulation of on-line signals
- Food for Thought: Can disclosure resources be used to gain system knowledge (data-driven attack)? cite:Park2019, cite:Yuan2020

*** Threat Analysis
   
*** Countermeasures: Defense in Depth 
   
- Prevention{{{reveallicense("./defense.meta","auto",nil,'none)}}}
  - Using cryptography/coding to preserve confidentiality (privacy)
- Detection
  - Fault Detection and Isolation (FDI)
  - Active Detection
- Resiliency
  - Off-line: Resilient system design
  - On-line: Secure information fusion, control
- Recovery
  - Software rejuvenation
  - Patching 
- ...

** Confidentiality


** Active Detection against Replay Attack

*** Stuxnet 
    
- NY times: /The worm itself now appears to have included two major components. One was designed to send Iran's nuclear centrifuges spinning wildly out of control. Another seems right out of the movies: *The computer program also secretly recorded what normal operations at the nuclear plant looked like, then played those readings back to plant operators*, like a pre-recorded security tape in a bank heist, so that it would appear that everything was operating normally while the centrifuges were actually tearing themselves apart./
 
*** System Description
   #+BEGIN_leftcol
    #+HTML: <div class="r-stack">
    #+ATTR_HTML: :class fragment fade-out :data-fragment-index 0
    [[./replaydiagramone.svg]]
    #+ATTR_HTML: :class fragment :data-fragment-index 0
    [[./replaydiagramtwo.svg]]
    #+HTML: </div>
- Assumptions: Linear Gaussian systems, Linear state estimator+state feedback, \(\chi_2\) failure detector.
   #+END_leftcol
   #+ATTR_REVEAL: :frag appear
   #+BEGIN_rightcol
   {{{revealimg("./replayunstableA.meta","Detection Rate v.s. Time",nil,nil,'none)}}}
   Not all system can detect replay attack!
   #+END_rightcol
 
*** Active Detection via Physical Watermarking
   #+BEGIN_leftcol
- Change the control law by adding a zero mean i.i.d. Gaussian watermarking signal \(\zeta(k)\):
\[ u(k) = \text{Optimal LQG Control}+ \zeta(k).\]
  {{{revealimg("./replaywithphywatermark.meta","40vh",nil,nil,'none)}}}
   #+END_leftcol
   #+BEGIN_rightcol
- Optimizing the covariance of \(\zeta(k)\):
\[\max\;Detection\;Performance,\,s.t.,\,Control\;Loss\leq \delta.\]
- Can be relaxed into semidefinite programming cite
- The problem can be solved on-line, without explicit system knowledge cite
- Other watermarking schemes (e.g., multiplicative watermark) cite
   #+END_rightcol
   
*** Simulation: Tennessee Eastman Process
   #+BEGIN_leftcol
- The TEP is created to provide a realistic industrial process for developing studying and evaluating process control technology.
  {{{revealimg("./simplifiedmodel.meta","40vh",nil,nil,'none)}}}
- The simplified model contain 4 inputs, 4 outputs and 7 internal states.
   #+END_leftcol
   #+BEGIN_rightcol
  {{{revealimg("./gng_te.meta","40vh",nil,nil,'none)}}}
  - Physical watermarks enable replay attack detection.
  - The optimal watermark signal and detector can be learned using data-driven approach.
   #+END_rightcol

** Secure State Estimation

*** Static State Estimation
- Sensor model:
\[\begin{bmatrix}
y_1\\
\vdots\\
y_m
\end{bmatrix} = Hx + noise + attack. \]
- The noise is *small* (zero mean Gaussian or bounded) but *ubiquitous*.
- The attack is \(p\)-*sparse* but can be *arbitrarily large*.
- Originally proposed by Peng et al.cite:Peng2009 in the context of DC power flow model.

*** Fundamental Limit for Noiseless Case
- The system is called \(p\)-observable if $H$ is full column rank even after removing rows corresponding to an arbitrary set of \(p\) sensors.
- The system is NOT \(p\)-observable \(\Rightarrow\) There exists undetectable attack.
- The system is NOT \(2p\)-observable \(\Rightarrow\) There exists unidentifiable attack.
- The system is NOT \(2p\)-observable \(\Rightarrow\) One cannot "securely" estimate the state with bounded error.
- The "secure" estimation problem is *NP-hard* in general cite
  
*** Secure Static Estimator
   #+BEGIN_leftcol
   - Estimator with Combinatorial Complexity cite, e.g.,
    \begin{align*}
      & \mathop{\textit{minimize}}\limits_{\hat x,a,w}&
      & \|w\|^2 \\
      &\text{subject to}&
      &y = H \hat x + w + a,\,\|a\|_0\leq p.
    \end{align*}
   - Require \(2p\)-observable to be "secure"
   - Achieves fundamental limit
   #+END_leftcol
   #+BEGIN_rightcol
   - Convex optimization based estimator cite
   \[\hat x = \argmin f_i (y_i - H_i\hat x)\]
   - Require stronger condition than \(2p\)-observable to generate "secure" estimate.
   #+END_rightcol
   
*** Simulation: IEEE 14-Bus System 
   #+BEGIN_leftcol
   - Consider the DC power flow model of IEEE 14-Bus system
   - The system has 27 sensors and 13 states
   {{{revealimg("./ieee14.meta","IEEE 14-Bus System","40vh",nil,'none)}}}
   - The power flow meter on the red line is being attacked
   #+END_leftcol
   #+BEGIN_rightcol
   {{{revealimg("./ieee14lasso.meta","Stuxnet Incident","40vh",nil,'none)}}}
   - With fine-tuned parameters, we can design a "good" estimator both in the *absence* and in the *presence* of attacks.
   #+END_rightcol
   
*** Dynamic State Estimation

** Robust System Topology Design
 
** Privacy 

*** Differential Privacy

*** Information Privacy



*** Homomorphic Encryption
    
*** Secure Multiparty Computing
   
* Applications
  
** Smart Transportation
   
** Cyber-Physical-Energy System

* Conclusion

   
** Bibliography
   :PROPERTIES:
   :CUSTOM_ID: bibliography
   :END:

   printbibliography:references.bib

   # Local Variables:
   # indent-tabs-mode: nil
   # org-src-preserve-indentation: t
   # End:
